export const GET_COLIS_REQ = 'GET_COLIS_REQ';
export const POST_COLIS_REQ = 'POST_COLIS_REQ';
export const PUT_COLIS_REQ = 'PUT_COLIS_REQ';
export const DELETE_COLIS_REQ = 'DELETE_COLIS_REQ';

export const GET_COLIS_RESP = 'GET_COLIS_RESP';
export const POST_COLIS_RESP = 'POST_COLIS_RESP';
export const PUT_COLIS_RESP = 'PUT_COLIS_RESP';
export const DELETE_COLIS_RESP = 'DELETE_COLIS_RESP';
